module unload cmake
module load cmake/3.16.2
module unload gcc
#module load gcc
module load ortools/9.4-c7-gcc9
module load gcc/9.3.0
#module load bison/3.0.5
module load flex
module load swig/4.0.0
module load boost/1.78.0
module load tcl/8.6.6
module load eigen3/3.3.7
module load lemon/1.3.1
#module load qt/5.11.0
module load spdlog
#
module load doxygen
module load valgrind
module load klayout
module load bison
module load llvm/10.0.1
